name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          port: 22
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls 
            pwd
            docker pull surendergupta/mean-backend:latest
            docker pull surendergupta/mean-frontend:latest
            cd /home/ubuntu/mean-app/
            docker-compose down
            docker-compose up -d
